### PR TITLE
Detect loop in linked list uploaded

### PR DESCRIPTION
**Pull request by Veeno-Rai**
this is solved using Floyd's cycle algorithms.

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
Please go through the contribution guide and check the repo before any commit

**Comment by Veeno-Rai** [comment]
Kindly explain in detail.

**Comment by Veeno-Rai** [comment]
kindly accept my pull request and merge it.
all  changes are welcomed

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add the output in your file

**Review by Veeno-Rai — COMMENTED** [review]
some changes has been done and output of code is also added.

**Comment by Veeno-Rai** [comment]
@bhumikatewary 
please review and merge!

**Review by bhumikatewary — APPROVED** [review]
looks good!

**Pull request merged**
