### PR TITLE
Longest Palindromic Substring

### PR DESCRIPTION
**Pull request by sahilsrivastava25**
@bhumikatewary Kindly review my PR Ma'am under HacktoberFest 2022

### CODE REVIEW

**Comment by sahilsrivastava25** [comment]
@bhumikatewary Ma'am I have added the desired output. Kindly review my PR under HacktoberFest 2022.
Screenshot (105)

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add the problem statement and an output in the file

**Comment by sahilsrivastava25** [comment]
@bhumikatewary Ma'am I added the output and problem in file as per the changes requested.
Kindly review my PR under Hacktoberfest 2022.

**Review by bhumikatewary — APPROVED** [review]
perfect

**Pull request merged**
