### PR TITLE
Create detect-cycle.cpp

### PR DESCRIPTION
**Pull request by s-bh**
C++ program to detect a loop in a singly linked list using fast and slow pointer method.
Issue #77

### CODE REVIEW

**Comment by s-bh** [comment]
hi, could you add the accepted label for it to be considered for hacktoberfest?

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please provide the problem statement and the output in your file

**Comment by s-bh** [comment]
hi, changes made as requested. Do check it out.

**Review by bhumikatewary — APPROVED** [review]
looks perfect!

**Pull request merged**
