### PR TITLE
Added the program Arithmetic Slices (Using DP)

### PR DESCRIPTION
**Pull request by cack195**

### CODE REVIEW

**Comment by cack195** [comment]
Hi
Kindly add the hacktoberfest label for my pull request
Thanks

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add a problem statement and an output in the file

**Comment by cack195** [comment]
Sure 
I'll do it

**Comment by cack195** [comment]
Hi
The requested changes have been made
Kindly check

**Review by bhumikatewary — APPROVED** [review]
looks perfect!

**Pull request merged**
