### PR TITLE
Implementation Of Queue.cpp

### PR DESCRIPTION
**Pull request by Shivam250702**
This is a CPP code regarding Implementation of queue.

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add the problem statement and an output in the file

**Comment by Shivam250702** [comment]
ok I am doing it

**Comment by Shivam250702** [comment]
Mam, the required changes are made please check

**Review by bhumikatewary — APPROVED** [review]
perfect

**Pull request merged**
