### PR TITLE
Create roman_numerals_to_int.py

### PR DESCRIPTION
**Pull request by JirroReo**
Added program to convert roman numeral strings to integer literals

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
Please check the contribution guide and make the changes

**Comment by JirroReo** [comment]
Alright, my bad

**Comment by bhumikatewary** [comment]
no problem, for your next PR you can do as mentioned

**Review by bhumikatewary — COMMENTED** [review]
PR approved

**Pull request merged**
