### PR TITLE
Added Expression Tree Implementation

### PR DESCRIPTION
**Pull request by mr-shitij**
Expression Evaluation Implementation Using Binary Search Tree

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
Please write the problem statement above your code

**Comment by NazimFilzer** [comment]
@bhumikatewary  Can i Add a Code to Arrays?

**Comment by bhumikatewary** [comment]
yes you can @NazimFilzer

**Comment by mr-shitij** [comment]
Done

**Comment by bhumikatewary** [comment]
Thank you for the contribution!

**Pull request merged**
