### PR TITLE
Create Rat_in_a_maze.cpp

### PR DESCRIPTION
**Pull request by roshan2152**
#103 Hey @bhumikatewary, please merge my file in your repository with hacktoberfest label.
Please assign me to this issue before merging. Thank you.

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please commit your file in the recursion folder of the repo

**Review by roshan2152 — COMMENTED** [review]
I've made the changes. @bhumikatewary

**Review by bhumikatewary — APPROVED** [review]
looks perfect!

**Comment by roshan2152** [comment]
@bhumikatewary please assign me this issue so that it will be accepted for hacktoberfest

**Comment by roshan2152** [comment]
@bhumikatewary please assign me this issue so that it will be accepted for hacktoberfest

**Pull request merged**
