### PR TITLE
Add PHP string examples

### PR DESCRIPTION
**Pull request by Aeka123**
This PR adds string examples to the PHP folder.

### CODE REVIEW

**Comment by Aeka123** [comment]
Wait, let me add problem descriptions to the files.

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add an output in the file

**Comment by Aeka123** [comment]
@bhumikatewary An output is included at the bottom of each file. Would you like it set up differently?

**Review by bhumikatewary — APPROVED** [review]

**Comment by bhumikatewary** [comment]
@Aeka123 everything's perfect

**Pull request merged**
