### PR TITLE
Added Kruskal Minimum Spanning Tree for a graph

### PR DESCRIPTION
**Pull request by krrahul23**

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add a problem statement and an output in the file

**Review by krrahul23 — COMMENTED** [review]
Added problem statement , input and output for the code.

**Review by krrahul23 — COMMENTED** [review]
Added problem statement , input and output for the code.

**Review by bhumikatewary — APPROVED** [review]
looks perfect!

**Comment by krrahul23** [comment]
Thanks for letting me participate 😃.

**Pull request merged**
