### PR TITLE
added intersection of two linked list question and its solution

### PR DESCRIPTION
**Pull request by Siddhesh4501**

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
Please add a problem statement and output in your file. Also check and delete duplicate code.

**Comment by Siddhesh4501** [comment]
No one added code for intersection of two linked list in C++.Thank You

**Comment by bhumikatewary** [comment]
is it intersection of sorted or unsorted linkedlists @Siddhesh4501 ?

**Comment by Siddhesh4501** [comment]
Yes

**Comment by bhumikatewary** [comment]
There are conflicts in your PR, please create a new PR and add a fresh file for LL only

**Pull request closed without merging**
