### PR TITLE
added dsu implementation

### PR DESCRIPTION
**Pull request by debapriya36**
Hi @bhumikatewary can you please check my pr

### CODE REVIEW

**Comment by debapriya36** [comment]
why reopend ?

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please provide a provide a problem statement and an output in your file

**Comment by debapriya36** [comment]
This is not a problem's solution code. This is only DSU(by rank +path compression) implementation code , so how can i provide o/p file and problem statement?

**Comment by debapriya36** [comment]
Only thing i can do is i can add code for graph problem where DSU is implementated ?

**Review by bhumikatewary — APPROVED** [review]
looks fine

**Comment by bhumikatewary** [comment]
no changes needed @debapriya36

**Pull request closed without merging**
