### PR TITLE
Create 23_MergekSortedLists.java

### PR DESCRIPTION
**Pull request by rohan-k11**
Created solution for Leetcode #23

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please check whether you are committing a duplicate code or not which is already present in the repo

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please check whether you are committing a duplicate code or not which is already present in the repo

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add an output in the file

**Review by rohan-k11 — COMMENTED** [review]
Added output

**Comment by bhumikatewary** [comment]
perfect

**Pull request merged**
