### PR TITLE
Added Articulation Point Issue Number 46

### PR DESCRIPTION
**Pull request by krrahul23**

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add a problem statement and an output in the file

**Review by krrahul23 — COMMENTED** [review]
Added explanation, problem statement, input and output for the code

**Review by bhumikatewary — APPROVED** [review]
looks perfect!

**Comment by krrahul23** [comment]
Thanks for letting me participate 😃.

**Pull request merged**
