### PR TITLE
Add Binary tree maximum path sum, Add gitignore file

### PR DESCRIPTION
**Pull request by sparsh9**

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
Please add a problem statement and output in your file

**Comment by sparsh9** [comment]
@bhumikatewary sure, will do

**Comment by sparsh9** [comment]
@bhumikatewary done, please let me know if anymore changes are required.

**Review by bhumikatewary — APPROVED** [review]
Nice! Thank you for the contribution

**Pull request merged**
