### PR TITLE
added short hand solution for python array missedSmallerInteger #83

### PR DESCRIPTION
**Pull request by srinivasthedeveloper**

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
for weird algorithm.cpp make changes in the existing file without already the existing code
also please add the problem statement and an output in the file

**Comment by srinivasNativeDeveloper** [comment]
I've just added the solution in python version and i haven't changed anything on the existing file other than the readme (updated as a relative link instead of absolute link) trust me @bhumikatewary existing files/codes won't break

**Comment by srinivasthedeveloper** [comment]
@bhumikatewary have fixed the conflicts now it's ready to be merged let me know if you have any other concerns.

**Review by bhumikatewary — APPROVED** [review]
perfect!

**Pull request merged**
