### PR TITLE
Delete Node in a Linked List

### PR DESCRIPTION
**Pull request by Jyotisaini-2001**
This is a Leetcode problem 237 based on Linked List.
hey @bhumikatewary please merge my pull request.

### CODE REVIEW

**Comment by akash-1107** [comment]
Please assign this to me

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add the problem statement and an output in the file

**Comment by Jyotisaini-2001** [comment]
> please add the problem statement and an output in the file

ok sure

**Comment by Jyotisaini-2001** [comment]
@bhumikatewary. I have done.

**Review by bhumikatewary — APPROVED** [review]
perfect

**Pull request merged**
