### PR TITLE
 Data Structures Full Notes

### PR DESCRIPTION
**Pull request by Mittalkabir**
In this Google drive link I attached my data Structures Full Notes

### CODE REVIEW

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
Create a folder named datastructure notes in the repo and then commit your file

**Comment by Mittalkabir** [comment]
Ok ☹️

**Comment by bhumikatewary** [comment]
I merged the PR, no changes are necessary

**Comment by Mittalkabir** [comment]
Thanku 🤗

**Pull request merged**
