### PR TITLE
Minimum Cost Spanning tree using greedy

### PR DESCRIPTION
**Pull request by Mitanshilodha**
kruskal's algorithm

### CODE REVIEW

**Comment by Mitanshilodha** [comment]
Mitanshilodha

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add the problem statement and an output in the file
also keep a valid pr name

**Review by bhumikatewary — CHANGES_REQUESTED** [review]
please add a problem statement and an output in the file

**Review by bhumikatewary — APPROVED** [review]
perfect

**Pull request merged**
