### PR TITLE
Painter's Partition/C++.

### PR DESCRIPTION
**Pull request by akhilesh5056**
@bhumikatewary kindly review my PR under Hacktoberfest 2022.

### CODE REVIEW

**Comment by bhumikatewary** [comment]
PR name is incorrect, follow contribution guide

**Comment by akhilesh5056** [comment]
@bhumikatewary For your convinience I am adding screenshot of output.
painter's partiton

**Comment by akhilesh5056** [comment]
@bhumikatewary Kindly review my PR under Hacktoberfest 2022.

**Comment by bhumikatewary** [comment]
this code has already been contributed, please work on some other code or create your own code and contribute

**Pull request closed without merging**
